import { Button, VerticalBox, Slider } from "std-widgets.slint";
import { MySlider } from "MySlider.slint";
import { HumidityPage } from "HumidityPage.slint";

export component AppWindow inherits Window {
    property <int> temperature: 20;
    property <string> humidity_info: "medium"; // Tracks the current humidity level
    property <string> current_page: "temperature"; // Tracks the current page

    width: 1024px;
    height: 600px;
    background: #141218;

    VerticalBox {
        horizontal-stretch: 1;
        vertical-stretch: 1;
        padding: 24px;

        // Header
        Text {
            vertical-stretch: 1;
            horizontal-stretch: 1;
            text: "Hello, Mateusz!";
            font-size: 32px;
            color: #ffffff;
        }

        HorizontalLayout {
            vertical-stretch: 9;
            horizontal-stretch: 1;
            spacing: 16px;

            // Left Side: Buttons Grid
            GridLayout {
                vertical-stretch: 1;
                horizontal-stretch: 4;
                spacing: 8px; // Add spacing between buttons
                
                Button {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    text: "Temperature: " + temperature + "°C";
                    row: 0;
                    col: 0;
                    checked: current_page == "temperature"; // Bind checked state to current_page
                    clicked => {
                        current_page = "temperature";
                    }
                }

                Button {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    text: "Humidity: " + humidity_info;
                    row: 0;
                    col: 1;
                    checked: current_page == "humidity"; // Bind checked state to current_page
                    clicked => {
                        current_page = "humidity";
                    }
                }

                Button {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    text: "Power consumption: 25.0kW/h";
                    row: 1;
                    col: 0;
                    checked: current_page == "power"; // Bind checked state to current_page
                    clicked => {
                        current_page = "power";
                    }
                }

                Button {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    text: "Air quality: good";
                    row: 1;
                    col: 1;
                    checked: current_page == "air_quality"; // Bind checked state to current_page
                    clicked => {
                        current_page = "air_quality";
                    }
                }
            }

            // Side Panel
            Rectangle {
                horizontal-stretch: 4;
                vertical-stretch: 1;
                background: #2c2c2c;
                Rectangle {
                    visible: current_page == "temperature";
                    Slider {
                        orientation: Orientation.vertical;
                        height: 100%;
                        horizontal-stretch: 1;
                        minimum: 0;
                        maximum: 30;
                        value: temperature;
                        visible: current_page == "temperature";

                        changed(value) => {
                            temperature = value;
                        }
                    }

                    Text {
                        text: round(temperature) + "°C";
                        font-size: 24px;
                        color: #ffffff;
                    }
                }

                // Humidity Page
                Rectangle {
                    visible: current_page == "humidity";
                    VerticalBox {
                        spacing: 8px; // Add spacing between buttons
                        Button {
                            text: "High";
                            checked: humidity_info == "high"; // Bind checked state to humidity_info
                            clicked => {
                                humidity_info = "high";
                            }
                        }

                        Button {
                            text: "Medium";
                            checked: humidity_info == "medium"; // Bind checked state to humidity_info
                            clicked => {
                                humidity_info = "medium";
                            }
                        }

                        Button {
                            text: "Low";
                            checked: humidity_info == "low"; // Bind checked state to humidity_info
                            clicked => {
                                humidity_info = "low";
                            }
                        }
                    }
                }

                // Power Consumption Page
                Rectangle {
                    visible: current_page == "power";
                    Text {
                        text: "power";
                        font-size: 24px;
                        color: #ffffff;
                    }
                }

                // Air Quality Page
                Rectangle {
                    visible: current_page == "air_quality";
                    Text {
                        text: "Air Quality: good";
                        font-size: 24px;
                        color: #ffffff;
                    }
                }
            }
        }
    }
}
