import { MainPage } from "MainPage.slint";
import { PerformancePage } from "PerformancePage.slint";

export component AppWindow inherits Window {
    background: #141218;
    full-screen: true;

    // state variable to control which page is shown
    property <bool> performanceStateEnabled: false;

    Rectangle { 
        if (!performanceStateEnabled) : MainPage {
            go-to-performance => { performanceStateEnabled = true; }
        }
        if (performanceStateEnabled) : PerformancePage {
            go-back => { performanceStateEnabled = false; }
        }
    }
}
