export component GlowingButton inherits Rectangle {
    in-out property <bool> checked: false;
    in-out property <color> glowColor: #ff0000;
    in-out property <string> text: "";

    callback clicked();

    drop-shadow-blur: checked ? 30px : 0px;
    background: #242424;
    drop-shadow-color: glowColor;
    border-radius: 20px;

    TouchArea {
        clicked => {
            root.clicked();
        }
    }

    Text {
        text: root.text;
        font-size: 16px;
        vertical-alignment: center;
        horizontal-alignment: center;
        width: parent.width;
        height: parent.height;
    }
}

export component Recipe inherits Window {
    GlowingButton {
        width: 200px;
        height: 200px;
    }
}
