export component GlowingButton inherits Rectangle {
    in-out property <bool> checked: false;
    in-out property <color> glowColor: #ff0000;
    in-out property <string> text: "";
    in-out property <image> iconSource;

    callback clicked();

    drop-shadow-blur: checked ? 30px : 0px;
    background: #242424;
    drop-shadow-color: glowColor;
    border-radius: 20px;

    TouchArea {
        clicked => {
            root.clicked();
        }
    }

    HorizontalLayout {
        // Make the layout itself “hug” its content…
        horizontal-stretch: 0;
        // …and center that within its parent
        alignment: center;                // centers children within this row
        spacing: 8px;

        Image {
            width: 32px;
            vertical-alignment: center;
            horizontal-alignment: center;
            source: iconSource;
        }

        Text {
            text: root.text;
            font-size: 16px;
            color: #ffffff;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}

export component Recipe inherits Window {
    GlowingButton {
        width: 200px;
        height: 200px;
    }
}
