import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component MySlider inherits Rectangle {
    in-out property<float> maximum: 100;
    in-out property<float> minimum: 0;
    in-out property<float> value;

    min-height: 24px;
    min-width: 100px;
    horizontal-stretch: 0;
    vertical-stretch: 0;

    border-radius: root.width/2;
    background: touch.pressed ? #eee: #ddd;
    border-width: 1px;
    border-color: root.background.darker(25%);

    handle := Rectangle {
        width: parent.width;
        height: self.width;
        border-width: 3px;
        border-radius: self.height / 2;
        background: touch.pressed ? #f8f: touch.has-hover ? #66f : #0000ff;
        border-color: self.background.darker(15%);
        y: (root.height - handle.height) * (root.value - root.minimum)/(root.maximum - root.minimum);

 Rectangle { min-width: 16px; min-height: 16px; /* @lsp:ignore-node */ }    }
    touch := TouchArea {
        moved => {
            if (self.enabled && self.pressed) {
                root.value = max(root.minimum, min(root.maximum,
                    root.value + (self.mouse-y - self.pressed-y) * (root.maximum - root.minimum) / root.width));
            }
        }
    }
}

export component Recipe inherits Window {
    HorizontalBox {
        alignment: start;
        slider := MySlider {
            maximum: 30;
        }
        Text {
            text: "Value: \{round(slider.value)}";
        }
    }
}