import { ScrollView } from "std-widgets.slint";
export component MyPower inherits Rectangle {
    in-out property <float> text;

    horizontal-stretch: 1;
    vertical-stretch: 1;
    background: #ff0000;

    Text {
        text: root.text;
    }
}

export component PowerPage inherits Flickable {
    // viewport_width: parent.width;s
    viewport_height: (120px * 6) + 100px;

    interactive: true;

    // array with 21 empty objects. Used only to create the same 21 rectangles. 
    for data[index] in [
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
    ]: Rectangle {
        y: 120px * floor(index / 3);
        x: 120px * Math.mod(index,3);
        width: 100px;
        height: 100px;
        background: #3a3a3a;
        border-radius: 10px;

        VerticalLayout {
            padding-top: 8px;
            padding-bottom: 8px;

            Image {
                source: @image-url("Icons/power.svg");
                vertical-stretch: 1;
                horizontal-alignment: center;
            }

            Text {
                text: "Outlet " + (index + 1);
                vertical-stretch: 1;
                horizontal-alignment: center;
                font-size: 16px;
                color: #ffffff;
            }

            Text {
                text: (index + 1) + " kW/h";
                vertical-stretch: 1;
                horizontal-alignment: center;
                font-size: 16px;
                color: #ffffff;
            }
        }
    }
}

export component Recipe inherits Window {
    PowerPage {
        width: 400px;
        height: 400px;
    }
}
