export component PowerConsumptionItem inherits Rectangle {
    in-out property <bool> performanceMode: false;
    in-out property <string> titleText;
    in-out property <string> valueText;
    in-out property <int> fontSize: 16;
    in-out property <int> imageRotation: 0;

    private property <int> rotationIntervalSeconds: 2;

    background: #3a3a3a;
    border-radius: 10px;

    VerticalLayout {
        padding-top: 8px;
        padding-bottom: 8px;

        Image {
            source: @image-url("Icons/power.svg");
            vertical-stretch: 1;
            horizontal-alignment: center;
            rotation-angle: imageRotation * 360deg;

            animate rotation-angle {
                duration: root.rotationIntervalSeconds * 1s;
            }
        }

        Text {
            text: titleText;
            vertical-stretch: 1;
            horizontal-alignment: center;
            font-size: fontSize * 1px;
            color: #ffffff;
        }

        Text {
            text: valueText;
            vertical-stretch: 1;
            horizontal-alignment: center;
            font-size: fontSize * 1px;
            color: #ffffff;
        }
    }

    timer:= Timer {
        interval: root.rotationIntervalSeconds * 1s;
        running: false;

        triggered => {
            root.rotate();
        }
    }


    // Startup trigger timer.
    Timer {
        interval: 50ms;
        running: true;
        triggered => {
            self.running = false;

            if (root.performanceMode) 
            {
                root.rotate();
                timer.running = true;
            }
        }
    }

    function rotate() {
        imageRotation += 1;
    }
}

export component Recipe inherits Window {
    PowerConsumptionItem {
        titleText: "Power Consumption";
        valueText: "1500 W";
        fontSize: 20;
        performanceMode: true;
    }
}
